name: Enforce CodeQL Usage
description: Policy action for enforcing the use of CodeQL via pull requests
inputs:
  default_branch:
    description: 'The default branch of the repository'
    required: true
    default: ${{ github.event.repository.default_branch }}
  org:
    description: 'The GitHub organization that owns the repository'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'The GitHub repository name'
    required: true
    default: ${{ github.event.repository.name }}
  message_not_found:
    description: 'The message to display on the pull request when CodeQL has not yet been configured'
    required: true
    default: "<h2>Code Scanning Analysis Not Found</h2>Your repository has not yet been configured to use CodeQL. Per VA policy your repository must use CodeQL to scan your source code for vulnerabilities. You can learn more about this requirement here: https://github.com/orgs/department-of-veterans-affairs/discussions/5<br><br>If this pull request configures CodeQL for the first time, after your pull requests CodeQL scan has completed, follow this link to re-run the policy check and select <code>Re-run all jobs</code> at the top of the page: <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}</a>"
  message_no_recent_analysis:
    description: 'The message to display on the pull request when CodeQL has not been run in the defined period'
    required: true
    default: "<h2>Code Scanning Analysis Not Found</h2>Your repository default branch has not been scanned with CodeQL in the last 7 days. Per VA policy your repository must use CodeQL to scan your source code for vulnerabilities at least once every 7 days against your default branch.<br><br>Once you have completed the scan against your default branch, follow this link to re-run the policy check and select <code>Re-run all jobs</code> at the top of the page: <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}</a>"
  period:
    description: 'The number of days to look back for CodeQL usage'
    required: true
    default: '7'
  pull_request:
    description: 'The pull request number'
    required: true
    default: ${{ github.event.pull_request.number }}
  token:
    description: 'The GitHub token to use for API requests'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
