name: Enforce Security Maintainers Usage
description: Policy action for enforcing the completion of the security_maintainers property in the repository settings
inputs:
  org:
    description: 'The GitHub organization that owns the repository'
    required: true
    default: ${{ github.repository_owner }}
  repo:
    description: 'The GitHub repository name'
    required: true
    default: ${{ github.event.repository.name }}
  message:
    description: 'The message to display on the pull request when security_maintainers has not yet been configured'
    required: true
    default: "<h2>Policy: Required Security Maintainers</h2>Your repository has not set the required <code>security_maintainers</code> property.<br><br>To support CSOC efforts, your repository must provide at least one valid email address or distribution group in the <code>security_maintainers</code> property for this repository. In the event of a security event, this property is used by incident responders to contact the responsible individual for your repositories security. Generally this is your ISSO, or in absence of an ISSO the admin of this repository responsible for owning security incidents.<br><br>You may update the <code>security_maintainers</code> property by having a repository admin navigate to the following link and selecting <code>Edit</code>: <a href='https://github.com/${{ github.repository }}/settings/custom-properties'>https://github.com/${{ github.repository }}/settings/custom-properties</a><br><br>Once you've updated this property, you may re-run this required check by navigating to the follow this link to re-run the policy check and select <code>Re-run all jobs</code> at the top of the page: <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}</a><br><br>You may also re-reun these required checks by simply commenting on this pull request with the following command:\n\n```bash\n/actions-bot rerun-required-workflows\n```"
  pull_request:
    description: 'The pull request number'
    required: true
    default: ${{ github.event.pull_request.number }}
  token:
    description: 'The GitHub token to use for API requests'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
