name: "Policy: Code Scanning"
on:
  pull_request:
jobs:
  enforce:
    name: Enforce Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Validate Code Scanning Policy
        uses: department-of-veterans-affairs/security-tools/enforce-code-scanning@main
