name: "Policy: Code Scanning Remediation"

on:
  pull_request:

jobs:
  enforce:
    name: Enforce Remediation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      security-events: read
    steps:
      - name: "Validate Policy: Remediation"
        uses: department-of-veterans-affairs/security-tools/enforce/remediation@main
